# packages/ddex-parser/bindings/python/Cargo.toml
[package]
name = "ddex-parser-python"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Marques Moo"]
license = "MIT"
publish = false

[lib]
name = "ddex_parser"
crate-type = ["cdylib"]

[dependencies]
ddex-core = { path = "../../../core" }
# Temporarily comment out until we have the parser core ready
# ddex-parser-core = { path = "../..", features = ["python"] }

pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
pyo3-asyncio-0-21 = { version = "0.21", features = ["tokio-runtime"], package = "pyo3-asyncio-0-21" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tokio = { version = "1.35", features = ["rt", "rt-multi-thread"] }
pythonize = "0.21"
numpy = { version = "0.21", optional = true }

[features]
default = ["dataframe"]
dataframe = ["numpy"]

[build-dependencies]
pyo3-build-config = "0.21"