#!/bin/bash
echo "📦 v0.3.0 RELEASE COMMANDS"
echo "=========================="
echo ""
echo "# 1. Final commit"
echo "git add -A"
echo "git commit -m 'Release v0.3.0 - Python native implementation, DataFrame fixes'"
echo ""
echo "# 2. Tag the release"
echo "git tag -a v0.3.0 -m 'Release v0.3.0"
echo "- Python native implementation (replaced mock)"
echo "- Complete DataFrame integration with 3 schemas"
echo "- Fixed namespace detection bugs"
echo "- Node.js and Python bindings production ready'"
echo ""
echo "# 3. Push to GitHub"
echo "git push origin main"
echo "git push origin v0.3.0"
echo ""
echo "# 4. Publish to crates.io (in order)"
echo "cd packages/ddex-core && cargo publish"
echo "sleep 30  # Wait for crates.io to index"
echo "cd ../ddex-parser && cargo publish"
echo "sleep 30"
echo "cd ../ddex-builder && cargo publish"
echo ""
echo "# 5. Publish to npm"
echo "cd packages/ddex-parser/bindings/node"
echo "npm publish --access public"
echo "cd ../../ddex-builder/bindings/node"
echo "npm publish --access public"
echo ""
echo "# 6. Publish to PyPI"
echo "cd packages/ddex-parser/bindings/python"
echo "twine upload target/wheels/ddex_parser-0.3.0-*.whl"
echo "cd ../../ddex-builder/bindings/python"
echo "twine upload target/wheels/ddex_builder-0.3.0-*.whl"
echo ""
echo "# 7. Create GitHub Release"
echo "gh release create v0.3.0 \\"
echo "  --title 'v0.3.0: Python Native Implementation' \\"
echo "  --notes-file CHANGELOG_v030.md \\"
echo "  packages/*/bindings/python/target/wheels/*.whl"
echo ""
echo "=========================="
echo "✅ Commands ready for execution"