# Enforce deterministic collections
disallowed-types = [
    # These types are non-deterministic and must not be used
    { path = "std::collections::HashMap", reason = "Use indexmap::IndexMap for deterministic iteration order" },
    { path = "std::collections::HashSet", reason = "Use indexmap::IndexSet for deterministic iteration order" },
    { path = "std::collections::BTreeMap", reason = "Use indexmap::IndexMap for consistent behavior" },
    { path = "std::collections::BTreeSet", reason = "Use indexmap::IndexSet for consistent behavior" },
]

# Warn on these patterns
warn = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::unimplemented",
    "clippy::todo",
]