[package]
name = "ddex-builder-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Marques Moo"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ddex-builder = { path = "../..", features = ["wasm"] }
ddex-core = { path = "../../../core", features = ["typescript"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3"