# cargo-deny configuration for supply chain security

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
skip = []

# Deny specific crates
deny = [
    { name = "openssl", reason = "Use rustls instead" },
    { name = "pcre", reason = "Use regex instead" },
]

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = ["GPL-3.0", "AGPL-3.0", "LGPL-3.0"]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "deny"
notice = "warn"
ignore = []