[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "ddex-builder"
version = "0.1.0"
description = "High-performance DDEX XML builder with deterministic output"
authors = [{name = "Kevin Marques Moo"}]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "pandas", "numpy"]

[tool.maturin]
python-source = "python"
module-name = "ddex_builder._ddex_builder"
features = ["pyo3/extension-module"]